package diagramdoc

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/guardana/control/internal/docscheck/frontmatter"
)

// Script is the generator every block names in its marker.
const Script = "scripts/gen-diagrams.go"

// Pages maps each page that holds a block to the name of the block it holds.
var Pages = map[string]string{
	"docs/concepts/enforcement-modes.md":      "modes",
	"docs/concepts/how-a-call-is-decided.md":  "fail-closed",
	"docs/concepts/evidence-and-the-spool.md": "chain",
}

// ErrBlock is wrapped by every refusal of a page's block.
var ErrBlock = errors.New("diagramdoc")

// Render returns the block for the named diagram, without its markers.
func Render(name string) ([]byte, error) {
	switch name {
	case "modes":
		return modeTable()
	case "fail-closed":
		return failClosedTable()
	case "chain":
		return chainDiagram()
	}
	return nil, fmt.Errorf("%w: no block named %q", ErrBlock, name)
}

// Splice replaces the one generated block of page, the lines between the
// marker naming Script and the closing marker, with block. A page with no
// such block, or with two, is refused, so a generator never writes a page it
// could not read back.
func Splice(page, block []byte) ([]byte, error) {
	open := []byte(frontmatter.GeneratedOpen + Script + " -->\n")
	closing := []byte(frontmatter.GeneratedClose + "\n")
	start := bytes.Index(page, open)
	if start < 0 {
		return nil, fmt.Errorf("%w: the page holds no block generated by %s", ErrBlock, Script)
	}
	if bytes.Contains(page[start+len(open):], open) {
		return nil, fmt.Errorf("%w: the page holds two blocks generated by %s", ErrBlock, Script)
	}
	rest := page[start+len(open):]
	end := bytes.Index(rest, closing)
	if end < 0 {
		return nil, fmt.Errorf("%w: the block generated by %s is not closed", ErrBlock, Script)
	}
	out := make([]byte, 0, len(page)-end+len(block))
	out = append(out, page[:start+len(open)]...)
	out = append(out, block...)
	out = append(out, rest[end:]...)
	return out, nil
}
