// Code generated by the dependency probe. DO NOT EDIT.

// The header above is Go's marker for generated code, and golangci-lint skips
// a file that carries it unless its configuration says otherwise. The probe
// plants its clock and I/O reads under that header, so a configuration that
// stopped examining generated files would leave every refusal below
// unreported.

package ioprobe

import (
	"context"
	"crypto/ed25519"
	"fmt"
	probeclock "time"

	"google.golang.org/protobuf/types/known/timestamppb"
)

// Each call below sits on a line of its own: golangci-lint keeps one issue per
// line, and the probe expects every one of them.

// DependencyProbeStamps reads the clock through a renamed import, which a
// pattern matched against the source text would miss.
func DependencyProbeStamps(start probeclock.Time) (probeclock.Time, probeclock.Duration, probeclock.Duration) {
	now := probeclock.Now()
	elapsed := probeclock.Since(start)
	left := probeclock.Until(start)
	return now, elapsed, left
}

// DependencyProbeWaits reads or waits on the clock through the timers, and
// stamps a message with the time the protobuf runtime reads.
func DependencyProbeWaits() *timestamppb.Timestamp {
	<-probeclock.After(0)
	probeclock.AfterFunc(0, func() {}).Stop()
	_ = probeclock.Tick(probeclock.Second)
	probeclock.NewTicker(probeclock.Second).Stop()
	probeclock.NewTimer(0).Stop()
	probeclock.Sleep(0)
	return timestamppb.Now()
}

// DependencyProbeBounded derives deadlines, which the context package takes
// from the clock.
func DependencyProbeBounded(ctx context.Context) (context.Context, context.CancelFunc, context.CancelFunc) {
	short, cancelShort := context.WithTimeout(ctx, probeclock.Second)
	_, cancelLong := context.WithDeadline(short, probeclock.Time{})
	return short, cancelShort, cancelLong
}

// DependencyProbeInput reads standard input and the zone database.
func DependencyProbeInput() (string, *probeclock.Location, error) {
	var line string
	if _, err := fmt.Scanln(&line); err != nil {
		return "", nil, err
	}
	zone, err := probeclock.LoadLocation("Europe/Warsaw")
	return line, zone, err
}

// DependencyProbeKey draws a key from the system's randomness, which
// crypto/ed25519 reaches through crypto/rand when it is given no reader.
func DependencyProbeKey() (ed25519.PublicKey, ed25519.PrivateKey, error) {
	return ed25519.GenerateKey(nil)
}
